### ISSUE TITLE
Use full name or remove starting delimiter

### ISSUE THREAD

**Issue by soffes** [usecanvas/canvas-native-3#6]
Since we have a two letter name, delimiter, and then metadata, we can either use the full name or remove the starting delimiter:

```
pg{}|Hello
```

or

```
paragraph|{}|Hello
```

Since we know the key will be 2 characters, having the starting delimiter is not necessary.

**Comment by jclem** [comment]
@soffes I like the delimiter between each component so that we can use `String#split`, which is significantly faster than `String#match`:

https://gist.github.com/jclem/e85a026c6d9dde57ba273f3a12d95123

![screenshot 2016-04-12 15 25 56](https://cloud.githubusercontent.com/assets/412282/14472823/0652630c-00c3-11e6-97d1-5a6286fece4a.png)

I realize we could `slice(2)`, then `split(SEPARATOR)`, but I'd rather be able to just `split(SEPARATOR)`. Doing `slice(2); split(SEPARATOR)` is also significantly slower than both `String#match` and `String#split`. Obviously, these benchmarks for for JavaScript, but I'd be surprised if they differed much in other runtimes, as far as perf ranking is concerned.
